name: ci-check
run-name: ci-check run by @${{ github.actor }}

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci-check:
    runs-on: ubuntu-latest
    # if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install packages
        run: bun install
      - name: Lint Check
        run: bun run lint
      - name: Build Check
        run: bun run build
  deploy:
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'Akatsuki1910' || github.actor == 'auto-add[bot]' }}
    needs: ci-check
    uses: ./.github/workflows/deploy.yml
